project_id = "vttnqcdbtwicrbsximfp"

[functions.generate-formation]
verify_jwt = false

[functions.generate-application]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.manage-database]
verify_jwt = false

[functions.agent-tasks]
verify_jwt = false
